version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run:
          command: docker run -e TEST=true -t vimuxegoto/abraka:0.5

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
